version: '3.1'

networks:
  todoapplab-network:

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - todoapplab-network
    restart: 
      on-failure
    mem_limit: 
      500M
  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - todoapplab-network
    restart: 
      on-failure
    mem_limit: 
      500M
  db:
    build:
      context: ./db
    ports:
      - 5430:5432
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sakalam18
      - todoapplab-network
    networks:
      - todoapplab-network
    mem_limit: 
      1G

